# Generated by Django 5.0.2 on 2024-06-03 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('post_id', models.PositiveIntegerField(primary_key=True, serialize=False, unique=True)),
                ('file_hash', models.CharField(max_length=64, unique=True)),
                ('file_extension', models.CharField(max_length=4)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('timestamp', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('tag', models.TextField(primary_key=True, serialize=False, unique=True)),
                ('posts', models.JSONField(blank=True, default=list)),
            ],
        ),
        migrations.CreateModel(
            name='UnderReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_hash', models.CharField(max_length=64, unique=True)),
                ('file_extension', models.CharField(max_length=4)),
            ],
        ),
    ]
